repository:
  # Repository name and description
  name: Terraform-ARC-cluster
  description: Terraform module for deploying GitHub Actions Runner Controller (ARC) on Kubernetes clusters
  homepage: https://github.com/idvoretskyi/Terraform-ARC-cluster
  
  # Repository visibility, can be 'public' or 'private'
  private: false
  
  # Repository features
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  
  # Default branch name
  default_branch: main
  
  # Allow squash merging
  allow_squash_merge: true
  
  # Allow merge commits
  allow_merge_commit: true
  
  # Allow rebase merging
  allow_rebase_merge: true
  
  # Allow auto-merge
  allow_auto_merge: false
  
  # Delete branch on merge
  delete_branch_on_merge: true
  
  # Enable discussions
  has_discussions: false
  
  # Topics to categorize the repository
  topics:
    - terraform
    - kubernetes
    - actions-runner-controller
    - github-actions
    - helm
    - cert-manager
    - devops
    - infrastructure-as-code

# Labels for issues and pull requests
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  
  - name: enhancement
    color: a2eeef
    description: New feature or request
  
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  
  - name: help wanted
    color: 008672
    description: Extra attention is needed

# Branch protection settings
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      
      # Require status checks to pass before merging
      required_status_checks:
        strict: true
        contexts:
          - "Terraform Format"
          - "Terraform Validate"
      
      # Enforce all configured restrictions for administrators
      enforce_admins: false
      
      # Restrict who can push to the branch
      restrictions: null
      
      # Require linear history
      required_linear_history: true
      
      # Allow force pushes
      allow_force_pushes: false
      
      # Allow deletions
      allow_deletions: false
      
      # Require signed commits
      required_signatures: false
