# Repository settings managed by https://github.com/apps/settings

repository:
  name: Terraform-ARC-cluster
  description: Terraform module for deploying GitHub Actions Runner Controller (ARC) on Kubernetes clusters
  homepage: https://github.com/idvoretskyi/Terraform-ARC-cluster
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  allow_auto_merge: false
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

# Branch protection
branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
      required_status_checks:
        strict: true
        contexts:
          - "Terraform Format"
          - "Terraform Validate"
      enforce_admins: false
      restrictions: null
      required_linear_history: true
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true

# Labels
labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: enhancement
    color: a2eeef
    description: New feature or request
  - name: good first issue
    color: 7057ff
    description: Good for newcomers
  - name: help wanted
    color: 008672
    description: Extra attention is needed
  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file
  - name: terraform
    color: 5319e7
    description: Related to Terraform configurations

# Repository topics
topics:
  - terraform
  - kubernetes
  - actions-runner-controller
  - github-actions
  - helm
  - devops
  - infrastructure-as-code
